# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Create a release on tag

on:
  push:
    tags: "*.*.*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod tidy

      - name: Ensure that the tests pass before building
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: make deps

      - name: Build all platforms
        run: |
          make release
          echo "VERSION=$(make -s version | grep Version | cut -d' ' -f2)" >> $GITHUB_ENV

      - name: Upload Linux amd64
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-${{ env.VERSION }}.linux.amd64
          path: ./build/cbzconcat-${{ env.VERSION }}.linux.amd64

      - name: Upload Linux x86
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-${{ env.VERSION }}.linux.x86
          path: ./build/cbzconcat-${{ env.VERSION }}.linux.x86

      - name: Upload Windows amd64
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-${{ env.VERSION }}.win_amd64.exe
          path: ./build/cbzconcat-${{ env.VERSION }}.win_amd64.exe

      - name: Upload Windows x86
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-${{ env.VERSION }}.win_x86.exe
          path: ./build/cbzconcat-${{ env.VERSION }}.win_x86.exe

      - name: Save version info
        run: |
          echo "$VERSION" > version.txt
      
      - name: Upload version info
        uses: actions/upload-artifact@v4
        with:
          name: version-info
          path: ./version.txt

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./
          merge-multiple: true

      - name: just print the tree for debug purposes
        run: find . -type f

      - name: Get version info
        run: |
          echo "VERSION=$(cat version.txt)" >> $GITHUB_ENV

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cbzconcat-${{ env.VERSION }}.linux.amd64
            cbzconcat-${{ env.VERSION }}.linux.x86
            cbzconcat-${{ env.VERSION }}.win_amd64.exe
            cbzconcat-${{ env.VERSION }}.win_x86.exe

      - name: Auto-merge to master
        if: success()  # Only if previous steps succeeded
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout master
          git merge develop
          git push origin master
