# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Create a release on tag

on:
  push:
    tags: "*.*.*"

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: go mod tidy

      - name: Ensure that the tests pass before building
        run: go test -v ./...

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: "1.20"

      - name: Install dependencies
        run: make deps

      - name: Build all platforms
        run: |
          make release
          VERSION=$(make -s version | grep Version | cut -d' ' -f2)

      - name: Upload Linux amd64
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-$VERSION.linux.amd64
          path: ./build/cbzconcat-$VERSION.linux.amd64

      - name: Upload Linux x86
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-$VERSION.linux.x86
          path: ./build/cbzconcat-$VERSION.linux.x86

      - name: Upload Windows amd64
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-$VERSION.win_amd64.exe
          path: ./build/cbzconcat-$VERSION.win_amd64.exe

      - name: Upload Windows x86
        uses: actions/upload-artifact@v4
        with:
          name: cbzconcat-$VERSION.win_x86.exe
          path: ./build/cbzconcat-$VERSION.win_x86.exe

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download artifacts
        uses: actions/download-artifact@v5
        with:
          path: ./
          merge-multiple: true

      - name: just print the tree for debug purposes
        run: find . -type f

      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            cbzconcat-$VERSION.linux.amd64
            cbzconcat-$VERSION.linux.x86
            cbzconcat-$VERSION.win_amd64.exe
            cbzconcat-$VERSION.win_x86.exe
